name: borcelle
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0  # Mantén esta versión
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.0.17
  model_viewer_plus: ^1.7.0
  path_provider: ^2.1.2
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/fotodeiconos/iconodeboda.jpg
    - assets/fotodeiconos/iconodequinceaños.jpg
    - assets/fotodeiconos/iconodecumpleaños.jpg
    - assets/fotodeiconos/iconodebautizo.png
    - assets/fotodeiconos/iconodebabyshower.png
    - assets/fotodepasteles/fotopastel1.jpg
    - assets/fotodepasteles/fotopastel2.jpeg
    - assets/fotodepasteles/fotopastel3.jpg
    - assets/fotodepasteles/fotopastel4.jpg
    - assets/fotodepasteles/fotopastel5.jpg
    - assets/fotodepasteles/fotopastel6.jpg
    - assets/fotodepasteles/pastelprimero.jpg
    - assets/fotodepasteles/banner1borcellitas.jpg
    - assets/fotodepasteles/banner2borcellitas.jpg
    - assets/fotodepasteles/iconoborcelle.jpg



