name: borcelle
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.0
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  model_viewer_plus: ^1.7.0
  path_provider: ^2.1.2
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  
flutter:
  uses-material-design: true

  assets:
    - assets/fotodeiconos/iconodeboda.jpg
    - assets/fotodeiconos/iconodequinceaños.jpg
    - assets/fotodeiconos/iconodecumpleaños.jpg
    - assets/fotodeiconos/iconodebautizo.png
    - assets/fotodeiconos/iconodebabyshower.png
    - assets/fotodepasteles/fotopastel1.jpg
    - assets/fotodepasteles/fotopastel2.jpeg
    - assets/fotodepasteles/fotopastel3.jpg
    - assets/fotodepasteles/fotopastel4.jpg
    - assets/fotodepasteles/fotopastel5.jpg
    - assets/fotodepasteles/fotopastel6.jpg
    - assets/fotodepasteles/pastelprimero.jpg
    - assets/fotodepasteles/banner1borcellitas.jpg
    - assets/fotodepasteles/banner2borcellitas.jpg
    - assets/fotodepasteles/iconoborcelle.jpg
    - assets/fotodepasteles/pasteldealmendra.jpg
    - assets/fotodepasteles/pasteldequesodebola.jpg
    - assets/fotodepasteles/pastelferrero.jpg
    - assets/fotodepasteles/pasteldemandarina.png
    - assets/fotodepasteles/
    - lib/Model3D/models/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/fotodepasteles/iconoborcelle.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/fotodepasteles/iconoborcelle.jpg"



